### PR TITLE
[Mobile] Post viewing page and article viewing page have been implemented

### PR DESCRIPTION
**Pull request by bbenginbestas**
***Description*:**
- View post, and view article have been implemented as talked in the mobile meetings.
image

***Tasks Done*:**
- [x] Implementing view article page
- [x] Implementing view post page

**Reviewer**: @enginoguzhansenol

### CODE REVIEW

**Comment by palahb** [comment]
Currently article page has comments although we have implemented our system as it does not have any comments under the artciles. So, article reading page should be redesigned. The following mockup we designed in CMPE 352 can be heplful:
Screen Shot 2022-10-25 at 12 27 50 (2)

**Comment by bbenginbestas** [comment]
Thank you for your insights. You are definitely correct in all of your points. I have committed new commits, fixed the things you mentioned, also added some features and did some bug fixes.

**Comment by palahb** [comment]
It seems that issues are solved. Thank you Bengin! After @enginoguzhansenol's review, we can merge the branch.

**Review by enginoguzhansenol — APPROVED** [review]
I viewed two created screens. Both of them are well designed. Thanks for your effort!

**Pull request merged**
