### PR TITLE
Frontend/feature/homepage pagination #367

### PR DESCRIPTION
**Pull request by Oozankilic**
At homepage, posts and articles are listed. They should be shown in a paginated order as mentioned in issue: [#367](https://github.com/bounswe/bounswe2022group5/issues/367)

### CODE REVIEW

**Comment by Keremgunduz7** [comment]
Looks good to me but couldn't figured it out that how it would look like from the code. Could you please share some screenshots before merging this PR.

**Review by yavuuzsameet — CHANGES_REQUESTED** [review]
Backend wants pageSize to be set to 10. That's why I set the parameter to 10 when initializing the file. I see that you have changed it to any number as parameter. We should leave it as 10.

**Comment by Oozankilic** [comment]
> Backend wants pageSize to be set to 10. That's why I set the parameter to 10 when initializing the file. I see that you have changed it to any number as parameter. We should leave it as 10.

I guess backend fixed pageSize number because it is working with any parameter now. Actually 10 for pageSize is pretty okey for me but with pagination, users can choose numbers of items per page, so the parameter changes. For clarification and @Keremgunduz7's request,  I'm adding some screenshots of the page. 
Screen Shot 2022-12-03 at 18 31 54
Screen Shot 2022-12-03 at 18 32 21
Screen Shot 2022-12-03 at 18 32 30
Screen Shot 2022-12-03 at 18 33 56

**Comment by Oozankilic** [comment]
Conflicts are fixed. Branch is ready to merge now

**Pull request merged**
