### PR TITLE
[Backend] Post search based on distance

### PR DESCRIPTION
**Pull request by irfanbozkurt**
***Description*:**

Based on my research last week (see finalized results [here](https://github.com/bounswe/bounswe2022group5/issues/440)), today I decided to implement [Spherical Law of Cosines in a query](https://en.wikipedia.org/wiki/Spherical_law_of_cosines) for distance-based search queries.

Here's the query:
Screen Shot 2022-12-17 at 16 57 57

***Todo's*:**
- [x] Find a way to add this custom query into Django's filtering
- [x] Implement the search endpoint

***Task Deadline*:** 17.12.2022 22:00

### CODE REVIEW

**Comment by irfanbozkurt** [comment]
I had to completely change the search endpoint to only send **raw queries** to the database. Although it was challenging, I found a way to implement desired functionality.

**Comment by irfanbozkurt** [comment]
Usage:
If you add a "dist" parameter to the post search endpoint, you should also pass "longitude" and "latitude" parameters; and the endpoint will only bring you posts that were created within "dist" kilometers.
Screen Shot 2022-12-17 at 21 41 14

**Comment by irfanbozkurt** [comment]
I added the usage information to the old documentation as well. Other teams can refer to there.

**Review by oguzhandemirelx — COMMENTED** [review]
A wonderful improvement, my friend. I tested the changes locally and had no issues. Merged!

**Pull request merged**
