### PR TITLE
Backend/feature/initial tables #199

### PR DESCRIPTION
**Pull request by irfanbozkurt**
- Added following [model classes](https://github.com/bounswe/bounswe2022group5/blob/backend/feature/initial_tables-%23199/app/backend/backend/models.py) 
    - User
    - Admin
    - MemberInfo
    - Member
    - Category
    - Doctor
    - Report
- Migrated these models to the database
    - In other words, database tables for these models are created
- Wrote [unit tests](https://github.com/bounswe/bounswe2022group5/blob/backend/feature/initial_tables-%23199/app/backend/tests/test_models.py) for model creations
- Turned DB password into an environment variable for safety reasons

### CODE REVIEW

**Review by mehmetemreakbulut — COMMENTED** [review]
All files were reviewed. 
Notes were written on PR

**Review by canberkboun9 — CHANGES_REQUESTED** [review]
Thank you for the time and effort!
- In the app/backend/backend/models.py file, line 62 should be retval += self.info.lastname
- line 27, line 28: null=True is the needed change, I think.

**Comment by irfanbozkurt** [comment]
Hey @canberkboun9, thanks for your review!

I fulfilled your requests with [this commit](https://github.com/bounswe/bounswe2022group5/pull/203/commits/51b5cf2aa8882c8eb007ebebbe299127b5b55cc4).

**Review by canberkboun9 — APPROVED** [review]
Required changes are done. I am unable to see another issue. We can merge this branch with master.

**Pull request merged**
