### PR TITLE
[Backend] Personal Info API Bugfix

### PR DESCRIPTION
**Pull request by canberkboun9**
***Description*:**
- User should be able to see their age in their profile page, and also be able to update them. I changed the code for age part. Now it's calculated instead of user changing it manually.

***Tasks Done*:**
- [x] get personal info bugfix
- [x] update personal info bugfix

***Reviewer*:**
- @mehmetemreakbulut 

**Notes:** 
- I think that age field is not needed for a user in the database.

***Issue*:** 
* See [Issue #430](https://github.com/bounswe/bounswe2022group5/issues/430)

### CODE REVIEW

**Comment by mehmetemreakbulut** [comment]
Hi, Canberk,
I will open a bugfix issue. Then I will review yok PR because there are some crucial bugs in app now.

**Comment by canberkboun9** [comment]
> Hi, Canberk, I will open a bugfix issue. Then I will review yok PR because there are some crucial bugs in app now.

Then, I should close this PR, and open a new one after that PR is merged.

**Review by mehmetemreakbulut — APPROVED** [review]
As I see you have added age calculation to user profile endpoint. Good point. Looks good to me!

**Comment by mehmetemreakbulut** [comment]
> > Hi, Canberk, I will open a bugfix issue. Then I will review yok PR because there are some crucial bugs in app now.
> 
> Then, I should close this PR, and open a new one after that PR is merged. However, I will wait until that PR is opened to avoid confusion.

No need to close PR. No conflict.

**Comment by canberkboun9** [comment]
> > > Hi, Canberk, I will open a bugfix issue. Then I will review yok PR because there are some crucial bugs in app now.
> > 
> > 
> > Then, I should close this PR, and open a new one after that PR is merged. However, I will wait until that PR is opened to avoid confusion.
> 
> No need to close PR. No conflict.

Yeah, I think you are right. Then, I will merge your PR first. We don't need to close this PR as well.

**Pull request merged**
