### PR TITLE
Practice app/feature/article-#105

### PR DESCRIPTION
**Pull request by canberkboun9**
I cloned the newest version of the master, opened my branch and made my commit and push for the `/article/api` endpoint.

### Done:

- GET and POST endpoints of the API are implemented.
- Tests in Postman are conducted.
- No conflicts occured.
- 
### To Do:

- Will work on unit tests and front-end (that will be mentioned in new issues for simplicity)

Reviewers: @makifyilmaz  @bbenginbestas can you review my implementation, please?

issue: [#105](https://github.com/bounswe/bounswe2022group5/issues/105)

### CODE REVIEW

**Comment by bbenginbestas** [comment]
It seems fine and there are no conflicts with the base branch. If @makifyilmaz approves too, we can merge the pull request.

**Review by makifyilmaz — APPROVED** [review]
Looks fine. We can merge it.

**Review by bbenginbestas — COMMENTED** [review]
We can delete the branch now.

**Review by bbenginbestas — COMMENTED** [review]
Deleted the branch

**Pull request merged**
