### PR TITLE
Practice app/feature/article info #97

### PR DESCRIPTION
**Pull request by makifyilmaz**
The initial version of article-info/api endpoint and its user interface is implemented as mentioned in issue #97 .

@canberkboun9 , @oguzhandemirelx  Can you review it?

### CODE REVIEW

**Review by canberkboun9 — APPROVED** [review]
Good work! I don't think it will collide with what I have been working on _article/_ endpoint. If it will, it will come out when we review that. I am merging this with the master.

**Comment by canberkboun9** [comment]
> Good work! I don't think it will collide with what I have been working on _article/_ endpoint. If it will, it will come out when we review that. I am merging this with the master.

Because git add . was used, these conflicts have occured. Using git add <individual-file-name> might resolve the issue. Maybe, we need to open a new branch and try again.

**Comment by makifyilmaz** [comment]
This conflict occured because of the wrong usage of git add command. Therefore I will switch to a new branch and make a new pull request from that branch.

**Comment by makifyilmaz** [comment]
The conflicts are resolved in a new branch and a new pull request (pr #125 ) is opened. Therefore I am closing this pull request.

**Pull request closed without merging**
