### PR TITLE
Practice app/feature/rate comment

### PR DESCRIPTION
**Pull request by enginoguzhansenol**
I implemented features for rating a comment with comment id. Some enhancements can be done in templates or views.  
Related issue: #109

### CODE REVIEW

**Review by bbenginbestas — APPROVED** [review]
Reviewed the files and everything seems set. Approving.

**Comment by yavuuzsameet** [comment]
There was a conflict, I removed the conflicts and approved

**Review by yavuuzsameet — COMMENTED** [review]
All done.

**Comment by enginoguzhansenol** [comment]
Thank you for editing. I am deleting this branch.

**Pull request merged**
